name: Generate Snake

on:
  schedule: 
      - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: Kaue404
          outputs: dist/snake.svg

      - name: Upload to repository
        uses: actions/upload-artifact@v2
        with:
          name: github-contribution-grid-snake
          path: dist/snake.svg
